---
uv_version: "0.11.21"
bin_path: "{{ ansible_env.HOME }}/.local/bin"
uv_install_path: "{{ bin_path }}/uv"
lang: "en_US.UTF-8"
uv_extra_args: ""
python_version: ""
uv_allow_python_fallback: false
uv_archive_legacy_venv: true
