---
- name: remove supervisor
  when: 
    - supervisor is defined
    - item.remove|d(False) == True
  become: yes
  supervisorctl: >
    name={{ project_name }}-{{ item.name }}:
    state=absent
  with_items: "{{ supervisor }}"

- name: update supervisor
  when: supervisor is defined
  become: yes
  command: supervisorctl update