---
# Initial setup tasks
- import_tasks: base.yml
  when: is_setup|d(False) == True

# Cleanup tasks for removing configuration
- import_tasks: cleanup.yml

# Main workflow
- name: Uvicorn | Stop uvicorn process
  when: uvicorn is defined
  become: yes
  supervisorctl: >
    name={{ project_name }}-{{ item.name }}-uvicorn:
    state=stopped
  with_items: "{{ uvicorn }}"
  tags:
    - stop
    - restart
    - never

- name: Uvicorn | Install uvicorn supervisor configuration.
  when: 
    - uvicorn is defined
    - item.remove|d(False) == False
  become: yes
  template: >
    src=supervisor.uvicorn.conf.j2
    dest=/etc/supervisor/conf.d/{{ project_name }}-{{ item.name }}-uvicorn.conf
    owner=root
    group=root
    mode=0644
    force=yes
  with_items: "{{ uvicorn }}"
  tags:
    - deploy

- name: Uvicorn | Update supervisor
  when: uvicorn is defined
  become: yes
  command: supervisorctl update

- name: Uvicorn | Start uvicorn process
  when: 
    - uvicorn is defined
    - item.remove|d(False) == False
  become: yes
  supervisorctl: >
    name={{ project_name }}-{{ item.name }}-uvicorn:
    state=started
  with_items: "{{ uvicorn }}"
  tags:
    - start
    - restart
    - never

- name: Uvicorn | Disable env switch
  when: 
    - uvicorn is defined
    - item.remove|d(False) == False
    - package_manager_command|d("") != "" 
  set_fact:
    uvicorn_env_switch: ""