---
- name: Pip | Install requirements
  command: '{{ virtualenv }}/bin/pip install -r {{ pip_requirements_file }}'
  environment:
    VIRTUAL_ENV: '{{ virtualenv }}'


- name: Pip | Set Package Manager Command Fact
  set_fact:
    package_manager_command: ""