---
- name: Install system packages
  become: yes
  apt: >
    pkg=rabbitmq-server
    state=present
    update-cache=yes
  tags:
    - setup

- name: Create vhost
  when: rabbitmq is defined
  become: yes
  rabbitmq_vhost:
    name: "{{ item }}"
    state: present
  with_items: "{{ rabbitmq.vhosts }}"
  tags:
    - setup

- name: Create user and set permissions
  when: 
    - rabbitmq is defined
    - item.remove|d(False) == False
  become: yes
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost }}"
    configure_priv: "{{ item.configure_priv }}"
    read_priv: "{{ item.read_priv }}"
    write_priv: "{{ item.write_priv }}"
    state: present
  with_items: "{{ rabbitmq.users }}"
  tags:
    - setup
