- name: Supervisor | Install system packages
  become: yes
  apt: >
    pkg=supervisor
    state=present
    update-cache=yes
  tags:
    - packages

- name: Supervisor | Enable on boot
  become: yes
  systemd: >
    name=supervisor
    enabled=yes
    state=started