---
- name: remove uvicorn
  when: 
    - uvicorn is defined
    - item.remove|d(False) == True
  become: yes
  supervisorctl: >
    name={{ project_name }}-{{ item.name }}-uvicorn:
    state=absent
  with_items: "{{ uvicorn }}"