---
- name: restart uvicorn
  when: 
    - uvicorn is defined
    - item.remove|d(False) == False
  become: yes
  supervisorctl: >
    name={{ project_name }}-{{ item.name }}-uvicorn:
    state=restarted
  with_items: "{{ uvicorn }}"

- name: remove uvicorn
  when: 
    - uvicorn is defined
    - item.remove|d(False) == True
  become: yes
  supervisorctl: >
    name={{ project_name }}-{{ item.name }}-uvicorn:
    state=absent
  with_items: "{{ uvicorn }}"

- name: update supervisor
  when: uvicorn is defined
  become: yes
  command: supervisorctl update