---
# Main deployment workflow
- name: Run database migrations
  when: django_commands.migrate|d(False) == True
  become_user:  "{{ project_user }}"
  django_manage: >
    command=migrate
    app_path={{ project_src }}
    settings={{ django_settings }}
    virtualenv={{ virtualenv }}
  environment: "{{ dot_env }}"
  tags:
    - deploy

- name: Install database fixtures
  when: django_commands.fixtures is defined
  become_user: "{{ project_user }}"
  django_manage: >
    command=loaddata
    fixtures={{ item }}
    app_path={{ project_src }}
    settings={{ django_settings }}
    virtualenv={{ virtualenv }}
  with_items: "{{ django_commands.fixtures }}"
  environment: "{{ dot_env }}"
  tags:
    - deploy

- name: Run collect static command
  when: django_commands.collectstatic|d(False) == True
  become_user: "{{ project_user }}"
  django_manage: >
    command=collectstatic
    app_path={{ project_src }}
    settings={{ django_settings }}
    virtualenv={{ virtualenv }}
  environment: "{{ dot_env }}"
  tags:
    - deploy