---
- name: Install Packages
  become: yes
  apt:
    pkg: "{{ ['postgresql','postgresql-contrib','python3-psycopg2', 'libpq-dev', 'acl'] }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: 
    - setup

- name: Create Database User
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_user: >
    user={{ postgresql.user }}
    password={{ postgresql.password }}
    port={{ postgresql.port }}
    role_attr_flags=CREATEDB,NOSUPERUSER
  tags: 
    - deploy

- name: Create Database
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_db: >
    name={{ postgresql.name }}
    owner={{ postgresql.user }}
    login_host={{ postgresql.host }}
    login_user={{ postgresql.user }}
    login_password={{ postgresql.password }}
    port={{ postgresql.port }}
  tags:
    - deploy