---
- name: Install Packages
  when: postgresql is defined
  become: yes
  apt:
    pkg: "{{ ['postgresql','postgresql-contrib','python3-psycopg2', 'libpq-dev', 'acl'] }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: 
    - setup

- name: Create Database User
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_user: >
    user={{ item.user }}
    password={{ item.password }}
    port={{ item.port }}
    role_attr_flags=CREATEDB,NOSUPERUSER
  with_items: "{{ postgresql }}"
  tags: 
    - deploy

- name: Create Database
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_db: >
    name={{ item.name }}
    owner={{ item.user }}
    login_host={{ item.host }}
    login_user={{ item.user }}
    login_password={{ item.password }}
    port={{ item.port }}
  with_items: "{{ postgresql }}"
  register: database_exists
  tags:
    - deploy

# - name: Import Database Backup
#   when:
#     - item.stdout.changed
#     - item.item.restore
#   postgresql_db: 
#     name: {{ item.item.name }}
#     state: restore
#     target: {{ item.item.restore }}
#   with_items: "{{ database_exists.results }}"
  