---
- name: Application Configuration
  hosts: 
    - '{{appservers_target|default("appservers")}}'
    - '{{taskservers_target|default("taskservers")}}'
  ignore_unreachable: "{{ ignore_unreachable|d(False) }}"
  roles:
    - role: application
      tags:
        - application
        - django
        - fastapi