---
- name: Project Folder Setup
  hosts: 
    - '{{appservers_target|default("appservers")}}'
    - '{{taskservers_target|default("taskservers")}}'
  ignore_unreachable: "{{ ignore_unreachable|d(False) }}"
  roles:
    - role: project
      tags:
        - project
