---
- name: memcached | Install system packages
  when: memcached is defined
  become: yes
  apt: >
    pkg=memcached
    state=present
    update-cache=yes
  tags:
    - setup

- name: memcached | Enable on boot
  when: memcached is defined
  become: yes
  systemd: >
    name=memcached
    enabled=yes
    state=started
  tags:
    - setup

- name: memcached | Install custom memcached config
  when: memcached is defined
  become: yes
  template: >
    src=memcached.conf.j2
    dest=/etc/memcached.conf
    backup=yes
    force=yes
  notify:
    - restart memcached
  tags:
    - setup